from . import product_template
from . import sale_order_line
from . import purchase_order_line
from . import stock_picking
from . import account_move_line
from . import stock_move
from . import res_partner
from . import hr_expense
from . import crm_lead
from . import project_project
from . import purchase_order
from . import sale_order
